INSERT INTO `super_rent`.`equipment` VALUES (1, 'Ski Rack', 'UNAVAILABLE', 'Thule', '2013-11-5', 'Universal', 1);
INSERT INTO `super_rent`.`equipment` VALUES (2, 'Ski Rack', 'AVAILABLE', 'CROSSBARS', '2013-11-6', 'VW Tiguan SE 4Motion', 1);
INSERT INTO `super_rent`.`equipment` VALUES (3, 'Ski Rack', 'AVAILABLE', 'SUBARU', '2013-11-7', 'TRIBECA', 1);
INSERT INTO `super_rent`.`equipment` VALUES (4, 'Ski Rack', 'AVAILABLE', 'Yakima', '2013-11-8', 'Ski Slope roof', 1);
INSERT INTO `super_rent`.`equipment` VALUES (5, 'Ski Rack', 'AVAILABLE', 'Thule', '2013-11-9', '751XT', 1);
INSERT INTO `super_rent`.`equipment` VALUES (6, 'Ski Rack', 'AVAILABLE', 'Yakima', '2013-11-10', 'ForkLift', 1);
INSERT INTO `super_rent`.`equipment` VALUES (7, 'Ski Rack', 'AVAILABLE', 'Thule', '2013-11-11', '651XT', 1);
INSERT INTO `super_rent`.`equipment` VALUES (8, 'Ski Rack', 'AVAILABLE', 'CROSSBARS', '2013-11-12', 'SUBARU 4Motion', 1);
INSERT INTO `super_rent`.`equipment` VALUES (9, 'Ski Rack', 'AVAILABLE', 'Yakima', '2013-11-13', 'SideWinder', 1);
INSERT INTO `super_rent`.`equipment` VALUES (10, 'Ski Rack', 'AVAILABLE', 'Yakima', '2013-11-14', 'CopperHead', 1);
INSERT INTO `super_rent`.`equipment` VALUES (11, 'Towing Equipment', 'UNAVAILABLE', 'OharazManualz', '2013-11-15', 'Towing Rope', 1);
INSERT INTO `super_rent`.`equipment` VALUES (12, 'Towing Equipment', 'AVAILABLE', '1megadeal', '2013-11-16', '651XT', 1);
INSERT INTO `super_rent`.`equipment` VALUES (13, 'Towing Equipment', 'AVAILABLE', 'Paul Politis Automotive Literature', '2013-11-8', '489YJH', 1);
INSERT INTO `super_rent`.`equipment` VALUES (14, 'Towing Equipment', 'AVAILABLE', 'Wholesale Direct Auto Parts', '2013-11-9', '652XT', 1);
INSERT INTO `super_rent`.`equipment` VALUES (15, 'Towing Equipment', 'AVAILABLE', 'Angstrom Autohaus', '2013-11-10', '490RJ', 1);
INSERT INTO `super_rent`.`equipment` VALUES (16, 'Towing Equipment', 'AVAILABLE', '2megadeal', '2013-11-11', '653XT', 1);
INSERT INTO `super_rent`.`equipment` VALUES (17, 'Towing Equipment', 'AVAILABLE', 'Paul Politis Automotive Literature', '2013-11-12', '489YJH', 1);
INSERT INTO `super_rent`.`equipment` VALUES (18, 'Towing Equipment', 'AVAILABLE', 'Wholesale Direct Auto Parts', '2013-11-13', '652XT', 1);
INSERT INTO `super_rent`.`equipment` VALUES (19, 'Towing Equipment', 'AVAILABLE', 'Angstrom Autohaus', '2013-11-14', '490RJ', 1);
INSERT INTO `super_rent`.`equipment` VALUES (20, 'Child Safety Seat', 'UNAVAILABLE', 'Tasca OEM Parts', '2010-5-9', 'VOLVO XJU-56', 1);
INSERT INTO `super_rent`.`equipment` VALUES (21, 'Child Safety Seat', 'AVAILABLE', 'Babytrend', '2010-7-10', 'BMW OMK-32', 1);
INSERT INTO `super_rent`.`equipment` VALUES (22, 'Child Safety Seat', 'AVAILABLE', 'Britax', '2010-9-10', 'WV ULT-954', 1);
INSERT INTO `super_rent`.`equipment` VALUES (23, 'Child Safety Seat', 'AVAILABLE', 'Dorel', '2010-11-11', 'VOLVO XJU-57', 1);
INSERT INTO `super_rent`.`equipment` VALUES (24, 'Child Safety Seat', 'AVAILABLE', 'Evenflo', '2011-1-12', 'BMW OMK-33', 1);
INSERT INTO `super_rent`.`equipment` VALUES (25, 'Child Safety Seat', 'AVAILABLE', 'Graco', '2013-11-13', 'WV ULT-955', 1);
INSERT INTO `super_rent`.`equipment` VALUES (26, 'Child Safety Seat', 'AVAILABLE', 'LearningCurve', '2013-11-14', 'VOLVO XJU-58', 1);
INSERT INTO `super_rent`.`equipment` VALUES (27, 'Child Safety Seat', 'AVAILABLE', 'PegPerego', '2010-5-9', 'BMW OMK-34', 1);
INSERT INTO `super_rent`.`equipment` VALUES (28, 'Child Safety Seat', 'AVAILABLE', 'SunshineKids', '2013-11-13', 'WV ULT-956', 1);
INSERT INTO `super_rent`.`equipment` VALUES (29, 'Lift Gate', 'AVAILABLE', 'PALFINGER Liftgates', '2017-5-20', 'Toyota UJT-172', 1);
INSERT INTO `super_rent`.`equipment` VALUES (30, 'Lift Gate', 'AVAILABLE', 'Anthony Liftgates', '2020-11-24', 'Honda KUJ-745', 1);
INSERT INTO `super_rent`.`equipment` VALUES (31, 'Lift Gate', 'AVAILABLE', 'Del/Ultron/Waltco Liftgate Parts', '2024-5-31', 'Ford KYH-098', 1);
INSERT INTO `super_rent`.`equipment` VALUES (32, 'Lift Gate', 'AVAILABLE', 'Maxon Liftgate Parts', '2027-12-6', 'Toyota UJT-173', 1);
INSERT INTO `super_rent`.`equipment` VALUES (33, 'Lift Gate', 'AVAILABLE', 'Tommy Gate Co. Liftgate Parts', '2031-6-12', 'Honda KUJ-746', 1);
INSERT INTO `super_rent`.`equipment` VALUES (34, 'Lift Gate', 'AVAILABLE', 'Venco Liftgate Parts', '2034-12-17', 'Ford KYH-099', 1);
INSERT INTO `super_rent`.`equipment` VALUES (35, 'Lift Gate', 'AVAILABLE', 'Thieman Liftgate Parts', '2038-6-23', 'Toyota UJT-174', 1);
