INSERT INTO `super_rent`.`equipment_type` VALUES ('Additional Luggage Rack', 800, 200);
INSERT INTO `super_rent`.`equipment_type` VALUES ('Child Safety Seat', 600, 100);
INSERT INTO `super_rent`.`equipment_type` VALUES ('DVD Players', 500, 150);
INSERT INTO `super_rent`.`equipment_type` VALUES ('GPS', 800, 200);
INSERT INTO `super_rent`.`equipment_type` VALUES ('Hand-controlled Steering', 600, 120);
INSERT INTO `super_rent`.`equipment_type` VALUES ('Lift Gate', 2000, 300);
INSERT INTO `super_rent`.`equipment_type` VALUES ('Portable Bicycle Racks', 800, 200);
INSERT INTO `super_rent`.`equipment_type` VALUES ('Protective Window Film', 400, 100);
INSERT INTO `super_rent`.`equipment_type` VALUES ('Ski Rack', 1000, 200);
INSERT INTO `super_rent`.`equipment_type` VALUES ('Tire Chains', 1000, 240);
INSERT INTO `super_rent`.`equipment_type` VALUES ('Towing Equipment', 1500, 200);
