INSERT INTO `super_rent`.`support` VALUES ('Additional Luggage Rack', 'COMPACT');
INSERT INTO `super_rent`.`support` VALUES ('Additional Luggage Rack', 'ECONOMY');
INSERT INTO `super_rent`.`support` VALUES ('Additional Luggage Rack', 'FULLSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Additional Luggage Rack', 'MIDSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Additional Luggage Rack', 'STANDARD');
INSERT INTO `super_rent`.`support` VALUES ('Additional Luggage Rack', 'SUV');
INSERT INTO `super_rent`.`support` VALUES ('Additional Luggage Rack', 'VAN');
INSERT INTO `super_rent`.`support` VALUES ('Child Safety Seat', 'COMPACT');
INSERT INTO `super_rent`.`support` VALUES ('Child Safety Seat', 'ECONOMY');
INSERT INTO `super_rent`.`support` VALUES ('Child Safety Seat', 'FULLSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Child Safety Seat', 'LUXURY');
INSERT INTO `super_rent`.`support` VALUES ('Child Safety Seat', 'MIDSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Child Safety Seat', 'PREMIUM');
INSERT INTO `super_rent`.`support` VALUES ('Child Safety Seat', 'STANDARD');
INSERT INTO `super_rent`.`support` VALUES ('Child Safety Seat', 'SUV');
INSERT INTO `super_rent`.`support` VALUES ('Child Safety Seat', 'VAN');
INSERT INTO `super_rent`.`support` VALUES ('DVD Players', 'COMPACT');
INSERT INTO `super_rent`.`support` VALUES ('DVD Players', 'ECONOMY');
INSERT INTO `super_rent`.`support` VALUES ('DVD Players', 'FULLSIZE');
INSERT INTO `super_rent`.`support` VALUES ('DVD Players', 'MIDSIZE');
INSERT INTO `super_rent`.`support` VALUES ('DVD Players', 'PREMIUM');
INSERT INTO `super_rent`.`support` VALUES ('DVD Players', 'STANDARD');
INSERT INTO `super_rent`.`support` VALUES ('DVD Players', 'SUV');
INSERT INTO `super_rent`.`support` VALUES ('DVD Players', 'VAN');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'BOXTRUCKS');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'CARGOVAN');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'COMPACT');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'ECONOMY');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'FOOT12');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'FOOT15');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'FOOT24');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'FULLSIZE');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'LUXURY');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'MIDSIZE');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'PREMIUM');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'STANDARD');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'SUV');
INSERT INTO `super_rent`.`support` VALUES ('GPS', 'VAN');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'BOXTRUCKS');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'CARGOVAN');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'COMPACT');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'ECONOMY');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'FOOT12');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'FOOT15');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'FOOT24');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'FULLSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'MIDSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'PREMIUM');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'STANDARD');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'SUV');
INSERT INTO `super_rent`.`support` VALUES ('Hand-controlled Steering', 'VAN');
INSERT INTO `super_rent`.`support` VALUES ('Lift Gate', 'BOXTRUCKS');
INSERT INTO `super_rent`.`support` VALUES ('Lift Gate', 'CARGOVAN');
INSERT INTO `super_rent`.`support` VALUES ('Lift Gate', 'FOOT12');
INSERT INTO `super_rent`.`support` VALUES ('Lift Gate', 'FOOT15');
INSERT INTO `super_rent`.`support` VALUES ('Lift Gate', 'FOOT24');
INSERT INTO `super_rent`.`support` VALUES ('Portable Bicycle Racks', 'ECONOMY');
INSERT INTO `super_rent`.`support` VALUES ('Portable Bicycle Racks', 'FULLSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Portable Bicycle Racks', 'MIDSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Portable Bicycle Racks', 'STANDARD');
INSERT INTO `super_rent`.`support` VALUES ('Portable Bicycle Racks', 'SUV');
INSERT INTO `super_rent`.`support` VALUES ('Portable Bicycle Racks', 'VAN');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'BOXTRUCKS');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'CARGOVAN');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'COMPACT');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'ECONOMY');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'FOOT12');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'FOOT15');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'FOOT24');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'FULLSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'LUXURY');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'MIDSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'PREMIUM');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'STANDARD');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'SUV');
INSERT INTO `super_rent`.`support` VALUES ('Protective Window Film', 'VAN');
INSERT INTO `super_rent`.`support` VALUES ('Ski Rack', 'COMPACT');
INSERT INTO `super_rent`.`support` VALUES ('Ski Rack', 'ECONOMY');
INSERT INTO `super_rent`.`support` VALUES ('Ski Rack', 'FULLSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Ski Rack', 'MIDSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Ski Rack', 'PREMIUM');
INSERT INTO `super_rent`.`support` VALUES ('Ski Rack', 'STANDARD');
INSERT INTO `super_rent`.`support` VALUES ('Ski Rack', 'SUV');
INSERT INTO `super_rent`.`support` VALUES ('Ski Rack', 'VAN');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'BOXTRUCKS');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'CARGOVAN');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'COMPACT');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'ECONOMY');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'FOOT12');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'FOOT15');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'FOOT24');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'FULLSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'LUXURY');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'MIDSIZE');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'PREMIUM');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'STANDARD');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'SUV');
INSERT INTO `super_rent`.`support` VALUES ('Tire Chains', 'VAN');
INSERT INTO `super_rent`.`support` VALUES ('Towing Equipment', 'BOXTRUCKS');
INSERT INTO `super_rent`.`support` VALUES ('Towing Equipment', 'CARGOVAN');
INSERT INTO `super_rent`.`support` VALUES ('Towing Equipment', 'FOOT12');
INSERT INTO `super_rent`.`support` VALUES ('Towing Equipment', 'FOOT15');
INSERT INTO `super_rent`.`support` VALUES ('Towing Equipment', 'FOOT24');
