INSERT INTO `super_rent`.`reserve_equipment` VALUES (24, 'Additional Luggage Rack', 200, 800);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (25, 'Child Safety Seat', 100, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (25, 'DVD Players', 150, 500);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (25, 'Portable Bicycle Racks', 200, 800);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (26, 'Portable Bicycle Racks', 200, 800);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (26, 'Protective Window Film', 100, 400);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (26, 'Ski Rack', 200, 1000);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (26, 'Tire Chains', 240, 1000);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (27, 'Hand-controlled Steering', 120, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (28, 'Hand-controlled Steering', 120, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (29, 'Child Safety Seat', 100, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (30, 'DVD Players', 150, 500);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (31, 'DVD Players', 150, 500);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (32, 'Child Safety Seat', 100, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (33, 'Child Safety Seat', 100, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (34, 'Hand-controlled Steering', 120, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (35, 'Hand-controlled Steering', 120, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (36, 'Child Safety Seat', 100, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (37, 'Child Safety Seat', 100, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (38, 'Child Safety Seat', 100, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (39, 'GPS', 200, 800);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (40, 'Hand-controlled Steering', 120, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (42, 'Lift Gate', 300, 2000);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (43, 'Protective Window Film', 100, 400);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (45, 'GPS', 200, 800);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (46, 'Additional Luggage Rack', 200, 800);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (46, 'Child Safety Seat', 100, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (46, 'DVD Players', 150, 500);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (46, 'GPS', 200, 800);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (46, 'Hand-controlled Steering', 120, 600);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (46, 'Portable Bicycle Racks', 200, 800);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (46, 'Protective Window Film', 100, 400);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (46, 'Ski Rack', 200, 1000);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (46, 'Tire Chains', 240, 1000);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (47, 'GPS', 200, 800);
INSERT INTO `super_rent`.`reserve_equipment` VALUES (48, 'Hand-controlled Steering', 120, 600);
